#include "tokenParser.hpp"
#include "../../../util/b64decoder.hpp"
#include "../../../util/delimKvpHelper.hpp"
#include "../../../util/stringSplitAndTrim.hpp"
#include "../../../util/timeUtils.hpp"

json parseAccessToken(std::string& accessToken) {
  // NOTE: There is no need to validate the token here, because it's
  // generated by Trino controller, which does its own authentication
  // to the identity provider that includes validating the token signature.
  // If this driver got a token from the Trino controller, we can just use it.
  std::vector<std::string> jwtComponents = stringSplitAndTrim(accessToken, '.');
  std::string jwtPayloadEncoded          = jwtComponents[1];
  std::string jwtPayloadDecoded          = fromBase64url(jwtPayloadEncoded);
  json jwtPayload                        = json::parse(jwtPayloadDecoded);
  return jwtPayload;
}
